plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/mnt/user-data/outputs/speedyheadshots"
publishOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]